(in-package :web-manager.handle)

(defun handle (plist-info)
  (format t "This is handle, now handle name:~A.~%" (getf plist-info :id))
  ;(zip-or-unzip plist-info)
  (do ((files (find-compressed (getf plist-info :path))
              (find-compressed (getf plist-info :path)))
       (i 0 (+ i 1)))
      ((or (not files) (= i 4)))
    (format t "new search compressed:~A~%" (+ i 1))
    (dolist (file files)
      (format t "extract ~A~%" file)
      (extract file (get-directory file) (getf plist-info :password))
      (format t "delete-file ~A~%" file)
      (delete-file file))
    (sleep 1)
    (format t "finish a compressed~%"))
  (format t "Finish handle"))

(in-package :cl-user)
